### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [dominicvogl/bwa-u4-feature-request#1]
Overall met expectations.

The document is well put together and explanatory.

So something I would add to the process of making this work.  You don't necessarily have to add or remove a css class.  

You can have the loader component that is animated by default.  When the spotify seach is submitted rendered the  animated component.  Then when it is completed replace the component with the search results.

**Comment by ghost** [comment]
Thank you for you feedback ;-)
I will think about your alternate way to realize the Loader. Sounds like a nice solution =)
